name: veryswagplugin
version: 2.0 Beta
author: sneakyspeedyboii
main: com.sneakyspeedyboii.veryswagplugin.register
api-version: 1.19
depend: [ProtocolLib]

commands:
  vspgui:
    description: Opens gui
    usage: /<command>
  gmc:
    description: changes to creative
    usage: /<command>
  gms:
    description: changes to survival
    usage: /<command>
  heal:
    description: heals
    usage: /<command>
  getuuid:
    description: gets uuid
    usage: /<command>
  toggledmg:
    description: toggles damage display
    usage: /<command>
  removedatacnt:
    description: removes persistent data container
    usage: /<command>
  getdata:
    description: sends player data
    usage: /<command>

permissions:
  veryswagplugin.commands:
    description: allows player to use commands
    default: true
  veryswagplugin.opcommands:
    description: allows player to use op commands
    default: op
  veryswagplugin.itemsuse:
    description: allows players to use items
    default: true